apiVersion: v1
kind: Service
metadata:
  name: { { include "weather.name" . } }
  labels: { { - include "weather.labels" . | nindent 4 } }
spec:
  ports:
    - port: 80
      targetPort: 80
  selector: { { - include "weather.labels" . | nindent 4 } }
