apiVersion: v2
name: construct-x-edge
description: Umbrella Helm chart for construct-x edge deployment with EDC and weather application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - construct-x
  - edge
  - edc
  - weather
  - umbrella
home: https://github.com/your-org/construct-x-edge-k8s
sources:
  - https://github.com/your-org/construct-x-edge-k8s
maintainers:
  - name: construct-x Team
    email: team@construct-x.org

dependencies:
  - name: ingress-nginx
    version: "4.8.3"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: nginx-ingress.enabled
  - name: edc
    version: "0.1.0"
    repository: "file://../edc"
    alias: edc
    condition: edc.enabled
  - name: weather
    version: "0.1.0"
    repository: "file://../weather"
    condition: weather.enabled
